export type UserDataType = {
  id: number;
  name: string;
  email: string;
  job_title: string;
  role: string;
};

export const UserData: UserDataType[] = [
  {
    id: 1,
    name: "Ryley Yarnold",
    email: "ryarnold0@unesco.org",
    job_title: "Chief Design Engineer",
    role: "Construction Manager",
  },
  {
    id: 2,
    name: "Sharl Call",
    email: "scall1@plala.or.jp",
    job_title: "Desktop Support Technician",
    role: "Construction Worker",
  },
  {
    id: 3,
    name: "Winona Goater",
    email: "wgoater2@bravesites.com",
    job_title: "Structural Analysis Engineer",
    role: "Construction Worker",
  },
  {
    id: 4,
    name: "Carol-jean Forri",
    email: "cforri3@engadget.com",
    job_title: "Professor",
    role: "Engineer",
  },
  {
    id: 5,
    name: "Elane Redmain",
    email: "eredmain4@a8.net",
    job_title: "Food Chemist",
    role: "Electrician",
  },
  {
    id: 6,
    name: "Norman Passion",
    email: "npassion5@sciencedaily.com",
    job_title: "Cost Accountant",
    role: "Engineer",
  },
  {
    id: 7,
    name: "Marilin Goudard",
    email: "mgoudard6@springer.com",
    job_title: "Senior Developer",
    role: "Electrician",
  },
  {
    id: 8,
    name: "Minetta Upchurch",
    email: "mupchurch7@cpanel.net",
    job_title: "Product Engineer",
    role: "Estimator",
  },
  {
    id: 9,
    name: "Vicki Treece",
    email: "vtreece8@nhs.uk",
    job_title: "Environmental Specialist",
    role: "Subcontractor",
  },
  {
    id: 10,
    name: "Renato Riveles",
    email: "rriveles9@dailymail.co.uk",
    job_title: "Director of Sales",
    role: "Electrician",
  },
  {
    id: 11,
    name: "Kelcie Chown",
    email: "kchowna@wordpress.org",
    job_title: "Tax Accountant",
    role: "Engineer",
  },
  {
    id: 12,
    name: "Alessandra Lawton",
    email: "alawtonb@nbcnews.com",
    job_title: "Technical Writer",
    role: "Subcontractor",
  },
  {
    id: 13,
    name: "Purcell Cluelow",
    email: "pcluelowc@indiatimes.com",
    job_title: "Payment Adjustment Coordinator",
    role: "Engineer",
  },
  {
    id: 14,
    name: "Loraine Kindleside",
    email: "lkindlesided@php.net",
    job_title: "Registered Nurse",
    role: "Supervisor",
  },
  {
    id: 15,
    name: "Annie Nazaret",
    email: "anazarete@i2i.jp",
    job_title: "Recruiting Manager",
    role: "Construction Manager",
  },
  {
    id: 16,
    name: "Hussein Meah",
    email: "hmeahf@blog.com",
    job_title: "Compensation Analyst",
    role: "Subcontractor",
  },
  {
    id: 17,
    name: "Ashlee Clitherow",
    email: "aclitherowg@angelfire.com",
    job_title: "Quality Engineer",
    role: "Construction Worker",
  },
  {
    id: 18,
    name: "Alfredo Janes",
    email: "ajanesh@yelp.com",
    job_title: "Editor",
    role: "Engineer",
  },
  {
    id: 19,
    name: "Rheta Gimlet",
    email: "rgimleti@techcrunch.com",
    job_title: "Electrical Engineer",
    role: "Project Manager",
  },
  {
    id: 20,
    name: "Matthew Heberden",
    email: "mheberdenj@umich.edu",
    job_title: "Desktop Support Technician",
    role: "Construction Worker",
  },
  {
    id: 21,
    name: "Xylia Adnam",
    email: "xadnamk@arizona.edu",
    job_title: "Administrative Assistant II",
    role: "Construction Worker",
  },
  {
    id: 22,
    name: "Sayres Martynov",
    email: "smartynovl@umn.edu",
    job_title: "Safety Technician I",
    role: "Project Manager",
  },
  {
    id: 23,
    name: "Alana Pariso",
    email: "aparisom@salon.com",
    job_title: "Director of Sales",
    role: "Construction Expeditor",
  },
  {
    id: 24,
    name: "Yolanda Splevings",
    email: "ysplevingsn@taobao.com",
    job_title: "Speech Pathologist",
    role: "Construction Worker",
  },
  {
    id: 25,
    name: "Tadio Attewell",
    email: "tattewello@cyberchimps.com",
    job_title: "Structural Analysis Engineer",
    role: "Estimator",
  },
  {
    id: 26,
    name: "Brianna Pymar",
    email: "bpymarp@tuttocitta.it",
    job_title: "Research Associate",
    role: "Surveyor",
  },
  {
    id: 27,
    name: "Derk Kniveton",
    email: "dknivetonq@buzzfeed.com",
    job_title: "Senior Cost Accountant",
    role: "Estimator",
  },
  {
    id: 28,
    name: "Worthington Garmey",
    email: "wgarmeyr@yellowpages.com",
    job_title: "Occupational Therapist",
    role: "Electrician",
  },
  {
    id: 29,
    name: "Lyda Jephcote",
    email: "ljephcotes@taobao.com",
    job_title: "Senior Editor",
    role: "Project Manager",
  },
  {
    id: 30,
    name: "Rice Blundin",
    email: "rblundint@drupal.org",
    job_title: "Pharmacist",
    role: "Surveyor",
  },
  {
    id: 31,
    name: "Far Elsmore",
    email: "felsmoreu@reddit.com",
    job_title: "Senior Quality Engineer",
    role: "Subcontractor",
  },
  {
    id: 32,
    name: "Annora Crennell",
    email: "acrennellv@bigcartel.com",
    job_title: "Analyst Programmer",
    role: "Construction Manager",
  },
  {
    id: 33,
    name: "Bess Sherr",
    email: "bsherrw@chron.com",
    job_title: "Software Consultant",
    role: "Electrician",
  },
  {
    id: 34,
    name: "Godard Burtwell",
    email: "gburtwellx@storify.com",
    job_title: "Professor",
    role: "Architect",
  },
  {
    id: 35,
    name: "Glennis Leavold",
    email: "gleavoldy@about.com",
    job_title: "VP Product Management",
    role: "Engineer",
  },
  {
    id: 36,
    name: "Maryanna MacCome",
    email: "mmaccomez@jimdo.com",
    job_title: "Help Desk Operator",
    role: "Architect",
  },
  {
    id: 37,
    name: "Granny Lofts",
    email: "glofts10@home.pl",
    job_title: "Editor",
    role: "Construction Foreman",
  },
  {
    id: 38,
    name: "Judd Joannet",
    email: "jjoannet11@tumblr.com",
    job_title: "Software Engineer IV",
    role: "Construction Manager",
  },
  {
    id: 39,
    name: "Karlotte Reddel",
    email: "kreddel12@imageshack.us",
    job_title: "Web Designer III",
    role: "Electrician",
  },
  {
    id: 40,
    name: "Boothe Kingsley",
    email: "bkingsley13@accuweather.com",
    job_title: "Financial Advisor",
    role: "Construction Expeditor",
  },
  {
    id: 41,
    name: "Marge Abramovitz",
    email: "mabramovitz14@tamu.edu",
    job_title: "Chemical Engineer",
    role: "Construction Worker",
  },
  {
    id: 42,
    name: "Glynn Corish",
    email: "gcorish15@phoca.cz",
    job_title: "Community Outreach Specialist",
    role: "Architect",
  },
  {
    id: 43,
    name: "Elsinore Blackhall",
    email: "eblackhall16@shinystat.com",
    job_title: "Senior Sales Associate",
    role: "Construction Expeditor",
  },
  {
    id: 44,
    name: "Sam Caunter",
    email: "scaunter17@slideshare.net",
    job_title: "General Manager",
    role: "Estimator",
  },
  {
    id: 45,
    name: "Kalil Hofner",
    email: "khofner18@hhs.gov",
    job_title: "Staff Scientist",
    role: "Estimator",
  },
  {
    id: 46,
    name: "Coralyn Humbatch",
    email: "chumbatch19@qq.com",
    job_title: "Administrative Assistant I",
    role: "Electrician",
  },
  {
    id: 47,
    name: "Carling Stubbington",
    email: "cstubbington1a@youtu.be",
    job_title: "Mechanical Systems Engineer",
    role: "Construction Worker",
  },
  {
    id: 48,
    name: "Richard Fletham",
    email: "rfletham1b@bbb.org",
    job_title: "Staff Scientist",
    role: "Construction Manager",
  },
  {
    id: 49,
    name: "Emili Paraman",
    email: "eparaman1c@unc.edu",
    job_title: "Junior Executive",
    role: "Electrician",
  },
  {
    id: 50,
    name: "Mallorie Tidbold",
    email: "mtidbold1d@51.la",
    job_title: "Systems Administrator IV",
    role: "Subcontractor",
  },
];
